### ISSUE TITLE
AttributeError: module 'annotated_types' has no attribute 'Not'

### ISSUE THREAD

**Issue by nitinmukesh** [TencentARC/MotionCtrl#37]
How to fix this

```
(venv) C:\ai\MotionCtrl>python -m app --share
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\MotionCtrl\app.py", line 7, in <module>
    import gradio as gr
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\routing.py", line 34, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\dependencies\models.py", line 5, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\security\__init__.py", line 4, in <module>
    from .http import HTTPAuthorizationCredentials as HTTPAuthorizationCredentials
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\security\http.py", line 16, in <module>
    class HTTPBasicCredentials(BaseModel):
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 223, in __new__
    complete_model_class(
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 568, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\main.py", line 670, in __get_pydantic_core_schema__
    return handler(source)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1308, in _common_field_schema
    schema = self._apply_annotations(
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2187, in new_handler
    schema = self._apply_single_annotation(schema, annotation)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2146, in _apply_single_annotation
    maybe_updated_schema = _known_annotated_metadata.apply_known_metadata(metadata, schema.copy())
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_known_annotated_metadata.py", line 302, in apply_known_metadata
    elif isinstance(annotation, (at.Predicate, at.Not)):
AttributeError: module 'annotated_types' has no attribute 'Not'(venv) C:\ai\MotionCtrl>python -m app --share
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\MotionCtrl\app.py", line 7, in <module>
    import gradio as gr
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\ai\MotionCtrl\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\routing.py", line 34, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\dependencies\models.py", line 5, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\security\__init__.py", line 4, in <module>
    from .http import HTTPAuthorizationCredentials as HTTPAuthorizationCredentials
  File "C:\ai\MotionCtrl\venv\lib\site-packages\fastapi\security\http.py", line 16, in <module>
    class HTTPBasicCredentials(BaseModel):
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 223, in __new__
    complete_model_class(
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 568, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\main.py", line 670, in __get_pydantic_core_schema__
    return handler(source)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1308, in _common_field_schema
    schema = self._apply_annotations(
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2187, in new_handler
    schema = self._apply_single_annotation(schema, annotation)
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2146, in _apply_single_annotation
    maybe_updated_schema = _known_annotated_metadata.apply_known_metadata(metadata, schema.copy())
  File "C:\ai\MotionCtrl\venv\lib\site-packages\pydantic\_internal\_known_annotated_metadata.py", line 302, in apply_known_metadata
    elif isinstance(annotation, (at.Predicate, at.Not)):
AttributeError: module 'annotated_types' has no attribute 'Not'
```

```



(venv) C:\ai\MotionCtrl>pip list
Package                     Version
--------------------------- ------------
aiofiles                    23.2.1
aiohappyeyeballs            2.4.3
aiohttp                     3.10.10
aiosignal                   1.3.1
altair                      5.4.1
annotated-types             0.5.0
antlr4-python3-runtime      4.9.3
anyio                       4.6.2.post1
async-timeout               4.0.3
attrs                       24.2.0
av                          13.1.0
certifi                     2024.8.30
charset-normalizer          3.4.0
click                       8.1.7
colorama                    0.4.6
contourpy                   1.3.0
cycler                      0.12.1
decorator                   4.4.2
decord                      0.6.0
einops                      0.8.0
exceptiongroup              1.2.2
fairscale                   0.4.13
fastapi                     0.115.4
ffmpy                       0.4.0
filelock                    3.16.1
fonttools                   4.54.1
frozenlist                  1.5.0
fsspec                      2024.10.0
ftfy                        6.3.1
gradio                      3.37.0
gradio_client               1.4.2
h11                         0.14.0
httpcore                    1.0.6
httpx                       0.27.2
huggingface-hub             0.26.2
idna                        3.10
imageio                     2.14.1
imageio-ffmpeg              0.4.7
Jinja2                      3.1.4
joblib                      1.4.2
jsonschema                  4.23.0
jsonschema-specifications   2024.10.1
kiwisolver                  1.4.7
kornia                      0.7.4
kornia_rs                   0.1.7
lightning-utilities         0.11.8
linkify-it-py               2.0.3
markdown-it-py              2.2.0
MarkupSafe                  2.1.5
matplotlib                  3.9.2
mdit-py-plugins             0.3.3
mdurl                       0.1.2
moviepy                     1.0.3
multidict                   6.1.0
mypy-extensions             1.0.0
narwhals                    1.13.2
numpy                       1.26.4
omegaconf                   2.3.0
open_clip_torch             2.29.0
opencv-python               4.8.0.74
orjson                      3.10.11
packaging                   24.1
pandas                      2.2.3
pillow                      10.4.0
pip                         23.0.1
plotly                      5.24.1
proglog                     0.1.10
propcache                   0.2.0
psutil                      5.9.5
pydantic                    2.9.0
pydantic_core               2.23.2
pydub                       0.25.1
pyparsing                   3.2.0
pyre-extensions             0.0.23
python-dateutil             2.9.0.post0
python-multipart            0.0.17
pytorch-lightning           1.9.0
pytz                        2024.2
PyYAML                      6.0.2
referencing                 0.35.1
regex                       2024.9.11
requests                    2.32.3
rpds-py                     0.20.1
safetensors                 0.4.5
scikit-learn                1.5.2
scipy                       1.14.1
semantic-version            2.10.0
setuptools                  65.5.0
six                         1.16.0
sniffio                     1.3.1
starlette                   0.41.2
taming-transformers-rom1504 0.0.6
tenacity                    9.0.0
threadpoolctl               3.5.0
timm                        1.0.11
tokenizers                  0.20.3
torch                       1.13.1+cu117
torchmetrics                1.5.1
torchvision                 0.14.1+cu117
tqdm                        4.66.6
transformers                4.46.2
typing_extensions           4.12.2
typing-inspect              0.9.0
tzdata                      2024.2
uc-micro-py                 1.0.3
urllib3                     2.2.3
uvicorn                     0.32.0
wcwidth                     0.2.13
websockets                  11.0.3
wheel                       0.44.0
xformers                    0.0.16
yarl                        1.17.1
```

**Comment by beikungg** [comment]
I fixed this issue after I demoted pydantic to version 2.6.0 (a random demoted version).
